apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: microdemo
resources:
  - namespace.yaml
  - app-configmap.yaml
  - postgres-secret.yaml
  - postgres-statefulset.yaml
  - mongo-statefulset.yaml
  - fastapi-deployment.yaml
  - node-deployment.yaml
  - ingress.yaml
