apiVersion: v1
kind: Service
metadata:
  name: node-svc
  namespace: microdemo
spec:
  selector:
    app: node-svc
  ports:
    - name: http
      port: 80
      targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-svc
  namespace: microdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-svc
  template:
    metadata:
      labels:
        app: node-svc
    spec:
      containers:
        - name: node
          image: node-svc:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: NODE_PORT
            - name: MONGO_URI
              value: mongodb://mongo.microdemo.svc.cluster.local:27017/appdb
          resources:
            requests:
              cpu: "100m"
            limits:
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: node-svc-hpa
  namespace: microdemo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: node-svc
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50   
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
        - type: Percent
          value: 100              
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 0  
      policies:
        - type: Percent
          value: 100               
          periodSeconds: 15
